#
# PHLU corporate routes
#
-
  name: 'Portrait Route Resolver'
  uriPattern: '{node}/portrait/{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'node':
      handler: 'TYPO3\Neos\Routing\FrontendNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false
    'contact':
      handler: 'PHLU\Corporate\Routing\ContactNodeRoutePartHandler'

-
  name: 'Dozpage Route Resolver'
  uriPattern: '{contact}'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'viewPortrait'
  routeParts:
    'contact':
      handler: 'PHLU\Corporate\Routing\ContactNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false

-
  name: 'Dozpage Route Resolver'
  uriPattern: '{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'viewPortrait'
  routeParts:
    'contact':
      handler: 'PHLU\Corporate\Routing\ContactNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false



-
  name: 'Project Detail Route Resolver'
  uriPattern: 'forschung/projekte/{project}/{title}<defaultUriSuffix>'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Project'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'project':
      handler: 'PHLU\Corporate\Routing\ProjectNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false




#
# PHLU corporate routes
#
-
  name: 'Portrait Route Builder'
  uriPattern: '{node}/portrait/{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'node':
      handler: 'TYPO3\Neos\Routing\FrontendNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false


#
# PHLU corporate routes
#
-
  name: 'Portrait Self Target Route Builder'
  uriPattern: '{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'viewPortrait'


#
# PHLU corporate routes
#
-
  name: 'Projects Route Builder'
  uriPattern: 'forschung/projekte/{project}/{title}<defaultUriSuffix>'
  defaults:
    '@package': 'PHLU.Corporate'
    '@controller': 'Project'
    '@format': 'html'
    '@action': 'load'

