##
# Neos Seo: XML Sitemap

-
  name: 'Neos Seo'
  uriPattern: '<NeosSeoSubroutes>'
  subRoutes:
    'NeosSeoSubroutes':
      package: 'Neos.Seo'
      variables:
        'xmlSitemapPath': 'sitemap.xml'

#
# Phlu corporate routes
#
#

-
  name: 'Portrait Route Resolver'
  uriPattern: '{node}/portrait/{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false
    'contact':
      handler: 'Phlu\Corporate\Routing\ContactNodeRoutePartHandler'

-
  name: 'Dozpage Route Resolver'
  uriPattern: '{contact}'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'viewPortrait'
  routeParts:
    'contact':
      handler: 'Phlu\Corporate\Routing\ContactNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false



-
  name: 'Dozpage Route Resolver'
  uriPattern: '{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'viewPortrait'
  routeParts:
    'contact':
      handler: 'Phlu\Corporate\Routing\ContactNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false



-
  name: 'Project Detail Route Resolver'
  uriPattern: 'forschung/projekte/{project}/{title}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Project'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'project':
      handler: 'Phlu\Corporate\Routing\ProjectNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false




#
# Phlu corporate routes
#
-
  name: 'Portrait Route Builder'
  uriPattern: '{node}/portrait/{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false



#
# Phlu corporate routes
#
-
  name: 'External Typo3 iframe Route Builder'
  uriPattern: '{node}/embedded/{identifier}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Embedded'
    '@format': 'html'
    '@action': 'view'
  routeParts:
    'node':
      handler: 'Neos\Neos\Routing\FrontendNodeRoutePartHandler'
      options:
        onlyMatchSiteNodes: false



#
# Phlu corporate routes  (use for link uri builder)
#
-
  name: 'Portrait Self Target Route Builder'
  uriPattern: '{contact}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Portrait'
    '@format': 'html'
    '@action': 'viewPortrait'


#
# Phlu corporate routes (use for link uri builder)
#
-
  name: 'Projects Route Builder'
  uriPattern: 'forschung/projekte/{project}/{title}<defaultUriSuffix>'
  defaults:
    '@package': 'Phlu.Corporate'
    '@controller': 'Project'
    '@format': 'html'
    '@action': 'load'


#
# Phlu corporate routes (use for link uri builder)
#
-
  name: 'weiterbildung studiengaenge Route Builder'
  uriPattern: 'weiterbildung/studiengaenge/{node}/{uri}<defaultUriSuffix>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Phlu\Corporate\Routing\CourseNodeRoutePartHandler'

#
# Phlu corporate routes (use for link uri builder)
#
-
  name: 'weiterbildung studiengaenge Route Builder'
  uriPattern: 'weiterbildung/studiengaenge/{node}/{year}/{uri}<defaultUriSuffix>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Phlu\Corporate\Routing\CourseNodeRoutePartHandler'

#
# Phlu corporate routes (use for link uri builder)
#
-
  name: 'weiterbildung veranstaltungen Route Builder'
  uriPattern: 'weiterbildung/veranstaltungen/{node}/{year}/{uri}<defaultUriSuffix>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Phlu\Corporate\Routing\CourseNodeRoutePartHandler'


#
# Phlu corporate routes (use for link uri builder)
#
-
  name: 'weiterbildung kurse Route Builder'
  uriPattern: 'weiterbildung/kurse/{node}/{uri}<defaultUriSuffix>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Phlu\Corporate\Routing\CourseNodeRoutePartHandler'

#
# Phlu corporate routes (use for link uri builder)
#
-
  name: 'weiterbildung kurse Route Builder'
  uriPattern: 'weiterbildung/kurse/{node}/{year}/{uri}<defaultUriSuffix>'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Phlu\Corporate\Routing\CourseNodeRoutePartHandler'


-
  name: 'Short url'
  uriPattern: '{node}'
  defaults:
    '@package':    'Neos.Neos'
    '@controller': 'Frontend\Node'
    '@action':     'show'
    '@format':     'html'
  routeParts:
    'node':
      handler:     'Phlu\Corporate\Routing\ShortUrlRoutePartHandler'



