TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'PHLU.Corporate': TRUE
    userInterface:
      requireJsPathMapping:
        'PHLU.Corporate/Handlers': 'resource://PHLU.Corporate/Public/JavaScript/Backend/Inspector/Handlers'
      translation:
        autoInclude:
          'PHLU.Corporate': ['NodeTypes/*']
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          # number of levels inside the structure tree which shall be loaded eagerly, at start.
          # 0 means unlimited
          loadingDepth: 0

  TypoScript:
    defaultContext:
      'PHLU.Corporate': 'PHLU\Corporate\Eel\Helper\NodeHelper'