TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'PHLU.Corporate': TRUE

    userInterface:
      translation:
        autoInclude:
          'PHLU.Corporate': ['NodeTypes/*']

  TypoScript:
    defaultContext:
      'PHLU.Corporate': 'PHLU\Corporate\Eel\Helper\NodeHelper'